// import { use, useState, useEffect, useRef } from "react";
import Head from 'next/head'
import Image from 'next/image'

import { useState } from 'react';
import NavBar from '../components/navbar';

import Link from 'next/link';



export default function Home() {
  const [navbar, setNavbar] = useState(false);
  return (
    <div className="bg-[#152022]  ">
      <Head>
        <title>Trizwit-NFTMockup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="Logo.svg" />
      </Head>

      {/* navbar start */}
      <div > <NavBar/> </div>
      {/* nav bar end */}

      <main >
      <div className='container h-screen bg-[#152022]'>

      </div>
        

      


      </main>




      
    
    </div>
  )
}
